[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = true
show_always = true

[hostname]
ssh_only = false
format =  "[$hostname](bold red) "
trim_at = ".fritz.box"
disabled = false

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "


[time]
disabled = true
format = ' [\[ $time \]]($style) '
time_format = "%T"
#utc_time_offset = "-5"
time_range = "00:00:00-24:00:00"
use_12hr = false
style = "bold green"
#time = 10:03:16
